kubernetes:
  packages:
    k8s_packages:
      - kubelet
      - kubeadm
      - kubectl
  centos:
    k8s_repo: https://pkgs.k8s.io/core:/stable:/v{{ vars["k8s"]["cluster_version"] }}/rpm/
    k8s_repo_key: https://pkgs.k8s.io/core:/stable:/v{{ vars["k8s"]["cluster_version"] }}/rpm/repodata/repomd.xml.key

  ubuntu:
    k8s_repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ vars["k8s"]["cluster_version"] }}/deb/ /
    k8s_repo_file: /etc/apt/sources.list.d/kubernetes.list
    k8s_repo_key: https://pkgs.k8s.io/core:/stable:/v{{ vars["k8s"]["cluster_version"] }}/deb/Release.key
    k8s_repo_keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

crio:
  ubuntu:
    crio_repo: deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ /
    crio_key: https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key
    crio_keyring: /etc/apt/keyrings/cri-o-apt-keyring.gpg
    crio_repofile: /etc/apt/sources.list.d/cri-o.list
  centos:
    crio_repo: https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/rpm/
    crio_key: https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/rpm/repodata/repomd.xml.key
containerd:
  centos:
    containerd_repo: https://download.docker.com/linux/centos/docker-ce.repo
  ubuntu:
    containerd_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    containerd_repo_key: https://download.docker.com/linux/ubuntu/gpg
    containerd_repo_key_file: /etc/apt/trusted.gpg.d/docker.gpg
