- name: This play provisions libvirt resources with terraform
  hosts: vm_host
  become: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: SELinux fix for running images in different folders
      when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 18)
      block:
        - name: Ensure security_driver is disabled
          ansible.builtin.lineinfile:
            line: 'security_driver = "none"'
            path: /etc/libvirt/qemu.conf
            state: present

        - name: Restart libvirtd service
          ansible.builtin.service:
            name: libvirtd
            state: restarted

    - name: Take care of systemd-resolved on F33 and Ubuntu hosts
      when:
        (ansible_distribution == 'Fedora' and ansible_distribution_major_version | int > 33) or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int > 18)
      block:
        - name: Ensure systemd-resolved config dir is present
          ansible.builtin.file:
            path: /etc/systemd/resolved.conf.d/
            state: directory
            mode: "0755"

        - name: Enable localdns if systemd-resolved is present
          ansible.builtin.template:
            src: systemd-resolved.j2
            dest: /etc/systemd/resolved.conf.d/{{ k8s.cluster_name | default('k8s-test', true) }}-local-kube.conf
            mode: "0755"
          notify:
            - Restart systemd-resolved

    - name: Ensure NM configuration directory exists
      ansible.builtin.file:
        path: /etc/NetworkManager/conf.d
        state: directory
        mode: "0755"

    - name: Ensure NM dnsmasq directory exists
      ansible.builtin.file:
        path: /etc/NetworkManager/dnsmasq.d
        state: directory
        mode: "0755"

    - name: Configure NetworkManager for local DNS
      ansible.builtin.copy:
        src: files/localdns.conf
        dest: /etc/NetworkManager/conf.d/{{ k8s.cluster_name | default('k8s-test', true) }}-localdns.conf
        mode: "0755"
      notify:
        - Restart NetworkManager

    - name: Configure NetworkManager for libvirt network
      ansible.builtin.template:
        src: templates/libvirt_dnsmasq.j2
        dest: /etc/NetworkManager/dnsmasq.d/{{ k8s.cluster_name | default('k8s-test', true) }}-libvirt_dnsmasq.conf
        mode: "0755"
      notify:
        - Restart NetworkManager

  handlers:
    - name: Restart systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
        enabled: true

    - name: Restart NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
