---
- name: Apply network plugin
  hosts: vm_host
  run_once: true
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Configure Calico
      when: k8s.network.cni_plugin == 'calico'
      block:
        - name: Download Calico manifest.
          ansible.builtin.get_url:
            url: "{{ item.url }}"
            dest: "{{ item.name }}"
            mode: "0664"
          loop:
            - name: /tmp/{{ k8s.cluster_name | default('k8s-test', true) }}/calico-operator.yaml
              url: "{{ cni_plugins.calico.calico_operator }}"
            - name: /tmp/{{ k8s.cluster_name | default('k8s-test', true) }}/calico-crd.yaml
              url: "{{ cni_plugins.calico.calico_crd }}"

        - name: Apply custom CIDR to calico installation manifest
          ansible.builtin.replace:
            path: /tmp/{{ k8s.cluster_name | default('k8s-test', true) }}/calico-crd.yaml
            regexp: 192.168.0.0\/16
            replace: "{{ k8s.network.pod_cidr }}"

        # - name: Temporary fix for non ascii char in Calico CRD (https://github.com/projectcalico/api/pull/46)
        #   ansible.builtin.replace:
        #     path: /tmp/{{ k8s.cluster_name | default('k8s-test', true) }}/calico-operator.yaml
        #     regexp: \’
        #     replace: ""

        - name: Apply calico manifests to the cluster.
          kubernetes.core.k8s:
            state: present
            src: "{{ item }}"
            kubeconfig: "{{ workspace_directory.base_path }}/clusters/{{ k8s.cluster_name | default('k8s-test', true) }}/admin.kubeconfig"
            wait: true
          loop:
            - /tmp/{{ k8s.cluster_name | default('k8s-test', true) }}/calico-operator.yaml
            - /tmp/{{ k8s.cluster_name | default('k8s-test', true) }}/calico-crd.yaml

    - name: Configure Cilium
      when: k8s.network.cni_plugin == 'cilium'
      block:
        - name: Add helm chart repository for Cilium
          kubernetes.core.helm_repository:
            name: "{{ item.name }}"
            repo_url: "{{ item.repo_url }}"
          loop:
            - name: "{{ cni_plugins.cilium.chart.name }}"
              repo_url: "{{ cni_plugins.cilium.chart.url }}"

        - name: Ensure Cilium helm chart is installed
          kubernetes.core.helm:
            name: cilium
            chart_ref: "{{ cni_plugins.cilium.chart.ref }}"
            kubeconfig: "{{ workspace_directory.base_path }}/clusters/{{ k8s.cluster_name | default('k8s-test', true) }}/admin.kubeconfig"
            release_namespace: kube-system
            update_repo_cache: true
            values:
              ipam:
                mode: kubernetes
            wait: true

    - name: Configure flannel
      when: k8s.network.cni_plugin == 'flannel'
      block:
        - name: Download flannel manifest
          ansible.builtin.get_url:
            url: "{{ cni_plugins.flannel.flannel_repo }}"
            dest: /tmp/{{ k8s.cluster_name | default('k8s-test', true) }}/kube-flannel.yaml
            mode: "0755"

        - name: Patch kube-flannel to use host-gw instead of vxlan
          ansible.builtin.replace:
            path: /tmp/{{ k8s.cluster_name | default('k8s-test', true) }}/kube-flannel.yaml
            regexp: "vxlan"
            replace: "host-gw"

        - name: Apply flannel manifests to the cluster.
          kubernetes.core.k8s:
            state: present
            src: /tmp/{{ k8s.cluster_name | default('k8s-test', true) }}/kube-flannel.yaml
            kubeconfig: "{{ workspace_directory.base_path }}/clusters/{{ k8s.cluster_name | default('k8s-test', true) }}/admin.kubeconfig"
            wait: true

    - name: Wait for core-dns pods to be up and running
      kubernetes.core.k8s:
        state: present
        api_version: v1
        kind: Deployment
        namespace: kube-system
        name: coredns
        kubeconfig: "{{ workspace_directory.base_path }}/clusters/{{ k8s.cluster_name | default('k8s-test', true) }}/admin.kubeconfig"
        wait: true
