---
- name: Cleanup playbook
  hosts: vm_host
  vars_files:
    - vars/k8s_cluster.yml
  tasks:
    - name: Set home directory
      ansible.builtin.set_fact:
        home_dir: "{{ ansible_env.HOME }}"

    - name: Destroy cluster VM
      community.general.terraform:
        force_init: true
        project_path: "{{ workspace_directory.base_path }}/clusters/{{ k8s.cluster_name | default('k8s-test', true) }}"
        state: absent
        variables:
          pool_name: "{{ k8s.cluster_name | default('k8s-test', true) }}"
          network_name: "{{ k8s.cluster_name | default('k8s-test', true) }}"
      become: true

    - name: Ensure images are deleted
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/OS-GenericCloud.qcow2
      become: true

    - name: Delete all created paths
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ workspace_directory.base_path }}/clusters/{{ k8s.cluster_name | default('k8s-test', true) }}"
      become: true

    - name: Cleanup local DNS config
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/NetworkManager/dnsmasq.d/{{ k8s.cluster_name | default('k8s-test', true) }}-libvirt_dnsmasq.conf
        - /etc/NetworkManager/conf.d/{{ k8s.cluster_name | default('k8s-test', true) }}-localdns.conf
      become: true

    - name: Restart NetworkManager and libvirtd
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - virtqemud
        - NetworkManager
      become: true
